# Generated by Django 3.2.17 on 2023-02-11 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('birthdate', models.DateField(verbose_name=['%d-%m-%Y'])),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('info', models.TextField(blank=True)),
                ('login', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('role', models.BooleanField(default=False)),
            ],
        ),
    ]
